In [1]:
import numpy as np


In [26]:
arr1 = np.arange(1,17).reshape(4,4)
print (arr1)
print(arr1[1:3,2:])
arr2 = arr1[1:2,:]*10
print (arr2)
print(arr1[(1,3),:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 7  8]
 [11 12]]
[[50 60 70 80]]
[[ 5  6  7  8]
 [13 14 15 16]]


In [11]:
arr2 = np.eye(3,3,2)
print (arr2)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
arr3 = np.array([True,False,True,False])
print (arr1[:,arr3])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [37]:
arr11 = np.arange(1,10).reshape(3,3)
arr12 = np.eye(3)
arr11 = arr11 + arr12
print (arr11)
print ("---")
arr11= arr11 + np.full((1,3),10)
print (arr11)
print ("---")
arr13 = arr11 * arr12
print (arr13)
print ("---")
arr14 = arr11.T
print(arr14)
print(np.dot(arr11,arr12))
print(np.cross(arr11,arr12))

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
---
[[12. 12. 13.]
 [14. 16. 16.]
 [17. 18. 20.]]
---
[[12.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 20.]]
---
[[12. 14. 17.]
 [12. 16. 18.]
 [13. 16. 20.]]
[[12. 12. 13.]
 [14. 16. 16.]
 [17. 18. 20.]]
[[  0.  13. -12.]
 [-16.   0.  14.]
 [ 18. -17.   0.]]


In [72]:
arr21 = np.arange(1,17).reshape(4,4)
print ('arr21 : ',arr21)

print ('sum : ',arr21.sum())
print ('mean :',arr21.mean())
print ('sum 1st column: ',arr21[:,:1].sum())
print ('mean 3rd row: ',arr21[2:3,:].mean())
print ('mean of center values: ',arr21[1:3,1:3].mean())
print ('product :',arr21.mean(axis=0))
print ('reveal : ',np.ravel(arr21)[5])


arr21 :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum :  136
mean : 8.5
sum 1st column:  28
mean 3rd row:  10.5
mean of center values:  8.5
product : [ 7.  8.  9. 10.]
reveal :  6


In [52]:
data = [[1, 88, 68, 25, 10, 'Sunny', False],
         [2, 84, 65, 31, 5, 'Cloudy', False],
         [3, 86, 66, 32, 5, 'Light Rain', False],
         [4, 89, 67, 26, 5, 'Rain', False],
         [5, 92, 70, 22, 10, 'Sunny', False],
         [6, 95, 71, 18, 20, 'Sunny', True],
          [7, 94, 69, 27, 10, 'Sunny', False]]


In [69]:
arr_temp_data = np.array(data,dtype = 'object')
print(arr_temp_data)

arr_high_low = np.array(arr_temp_data[:,1:3],dtype=int)
print(arr_high_low)

arr_high_low.mean(axis=1)

[[1 88 68 25 10 'Sunny' False]
 [2 84 65 31 5 'Cloudy' False]
 [3 86 66 32 5 'Light Rain' False]
 [4 89 67 26 5 'Rain' False]
 [5 92 70 22 10 'Sunny' False]
 [6 95 71 18 20 'Sunny' True]
 [7 94 69 27 10 'Sunny' False]]
[[88 68]
 [84 65]
 [86 66]
 [89 67]
 [92 70]
 [95 71]
 [94 69]]


array([78. , 74.5, 76. , 78. , 81. , 83. , 81.5])

In [81]:
arr41 = np.arange(1,10).reshape(3,3)
arr42 = np.roll(arr41,1)

print (arr42)
print (arr41[:,1].argsort())
print (arr41 > 4)


[[9 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[False False False]
 [False  True  True]
 [ True  True  True]]
