In [1]:
import numpy as np

In [2]:

s = np.array([
    [0,0,1,7,0,0,2,3,5],
    [0,9,0,3,0,0,6,0,8],
    [0,0,0,0,0,4,1,0,0],
    [0,7,9,0,0,9,0,0,3],
    [5,3,9,0,0,0,8,1,6],
    [8,0,0,5,0,0,0,9,0],
    [0,0,3,1,0,0,0,0,0],
    [6,0,4,0,0,7,0,2,0],
    [9,1,7,0,0,6,5,0,0]])
s


array([[0, 0, 1, 7, 0, 0, 2, 3, 5],
       [0, 9, 0, 3, 0, 0, 6, 0, 8],
       [0, 0, 0, 0, 0, 4, 1, 0, 0],
       [0, 7, 9, 0, 0, 9, 0, 0, 3],
       [5, 3, 9, 0, 0, 0, 8, 1, 6],
       [8, 0, 0, 5, 0, 0, 0, 9, 0],
       [0, 0, 3, 1, 0, 0, 0, 0, 0],
       [6, 0, 4, 0, 0, 7, 0, 2, 0],
       [9, 1, 7, 0, 0, 6, 5, 0, 0]])

In [4]:
def isvaluecorrect(s,v,i,j):
    if s[i][j] != 0:
        return 0
    for n in range(len(s)):
        if s[i][n]== v or s[n][j]==v:
            return 0
    a = np.sqrt(len(s))
    x = int(i//a)*3
    y = int(j//a)*3
    for n in range(x,x+3):       
        for m in range(y,y+3):        
            if s[n][m] == v:
                return 0
    return v

In [15]:
isvaluecorrect(s,7,4,3)

0

In [6]:
def solve(s):
    for i in range(len(s)):
        for j in range(len(s)):
            if s[i][j] ==0:
                for n in range(1,len(s)+1):
                    if isvaluecorrect(s,n,i,j) != 0:
                        s[i][j]= n
                        solve(s)
                        s[i][j]=0
                return    
    print (s)  

In [48]:
def check_solution(s):
    for i in range(len(s)):
        for j in range(len(s)):
            if isvaluecorrect(s,s[i][j],i,j)==0:
                print ('incorrect solution')                
                return
    print ('Correct Solution')

In [16]:
print ('Puzzle:')
print (s)
print ('solution:')
solve(s)



Puzzle:
[[0 0 1 7 0 0 2 3 5]
 [0 9 0 3 0 0 6 0 8]
 [0 0 0 0 0 4 1 0 0]
 [0 7 9 0 0 9 0 0 3]
 [5 3 9 0 0 0 8 1 6]
 [8 0 0 5 0 0 0 9 0]
 [0 0 3 1 0 0 0 0 0]
 [6 0 4 0 0 7 0 2 0]
 [9 1 7 0 0 6 5 0 0]]
solution:
[[4 6 1 7 9 8 2 3 5]
 [7 9 5 3 2 1 6 4 8]
 [3 2 8 6 5 4 1 7 9]
 [1 7 9 8 6 9 4 5 3]
 [5 3 9 4 7 2 8 1 6]
 [8 4 6 5 1 3 7 9 2]
 [2 8 3 1 4 5 9 6 7]
 [6 5 4 9 8 7 3 2 1]
 [9 1 7 2 3 6 5 8 4]]


In [8]:
def move(s,e,n=0):
    print ('move disk {} from position {} to position {} !'.format(n,s,e))

In [9]:
move ('A','B')

move disk 0 from position A to position B !


In [8]:
def movevia(a,v,b):
    move(a,v)
    move(v,b)

In [15]:
movevia('A','V','B')

move disk 0 from position A to position V !
move disk 0 from position V to position B !


In [17]:
def hanoi(n,a,b,c):
    if n ==0:
        pass
    else:
        hanoi(n-1,a,c,b)
        move(a,b,n)
        hanoi(n-1,b,a,c)

In [18]:
hanoi(5,'A','B','C')

move disk 1 from position A to position B !
move disk 2 from position A to position C !
move disk 1 from position C to position A !
move disk 3 from position A to position B !
move disk 1 from position B to position C !
move disk 2 from position B to position A !
move disk 1 from position A to position B !
move disk 4 from position A to position C !
move disk 1 from position C to position A !
move disk 2 from position C to position B !
move disk 1 from position B to position C !
move disk 3 from position C to position A !
move disk 1 from position A to position B !
move disk 2 from position A to position C !
move disk 1 from position C to position A !
move disk 5 from position A to position B !
move disk 1 from position B to position C !
move disk 2 from position B to position A !
move disk 1 from position A to position B !
move disk 3 from position B to position C !
move disk 1 from position C to position A !
move disk 2 from position C to position B !
move disk 1 from position B to p