In [43]:
import numpy as np

In [44]:

s = np.array([
    [0,0,1,7,0,0,2,3,5],
    [0,9,0,3,0,0,6,0,8],
    [0,0,0,0,0,4,1,0,0],
    [0,7,9,0,0,9,0,0,3],
    [5,3,9,0,0,0,8,1,6],
    [8,0,0,5,0,0,0,9,0],
    [0,0,3,1,0,0,0,0,0],
    [6,0,4,0,0,7,0,2,0],
    [9,1,7,0,0,6,5,0,0]])
s


array([[0, 0, 1, 7, 0, 0, 2, 3, 5],
       [0, 9, 0, 3, 0, 0, 6, 0, 8],
       [0, 0, 0, 0, 0, 4, 1, 0, 0],
       [0, 7, 9, 0, 0, 9, 0, 0, 3],
       [5, 3, 9, 0, 0, 0, 8, 1, 6],
       [8, 0, 0, 5, 0, 0, 0, 9, 0],
       [0, 0, 3, 1, 0, 0, 0, 0, 0],
       [6, 0, 4, 0, 0, 7, 0, 2, 0],
       [9, 1, 7, 0, 0, 6, 5, 0, 0]])

In [51]:
def isvaluecorrect(s,v,i,j):
    if s[i][j] != 0:
        return False
    for n in range(len(s)):
        if s[i][n]== v or s[n][j]==v:
            return False
    a = int(np.sqrt(len(s)))
    x = int(i//a)*a
    y = int(j//a)*a
    for n in range(x,x+a):       
        for m in range(y,y+a):        
            if s[n][m] == v:
                return False
    return True

In [50]:
isvaluecorrect(s,2,4,3)

True

In [ ]:
def isvalid(s):
    n = len(s)
    for i in range 
    

In [62]:
def isvaluecorrect1(board,v,i,j):
    if board[i][j] != '.':
        return False
    for n in range(len(board)):
        if board[i][n]== v or board[n][j]==v:
            return False

    x = int(i//3)*3
    y= int(j//3)*3
    for n in range(x,x+3):       
        for m in range(y,y+3):        
            if board[n][m] == v:
                return False
    return True
        
def solve (board): 
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j] ==0:
                for n in range(1,len(board)+1):                    
                    if  isvaluecorrect1(board,n,i,j) :
                        board[i][j] = n
                        solve(board)
                        board[i][j] = 0
                return False
    print (board)
    return(True)
                              

In [48]:
def check_solution(s):
    for i in range(len(s)):
        for j in range(len(s)):
            if isvaluecorrect(s,s[i][j],i,j)==0:
                print ('incorrect solution')                
                return
    print ('Correct Solution')

In [63]:
print ('Puzzle:')
print (s)
print ('solution:')
solve(s)
print(s)



Puzzle:
[[0 0 1 7 0 0 2 3 5]
 [0 9 0 3 0 0 6 0 8]
 [0 0 0 0 0 4 1 0 0]
 [0 7 9 0 0 9 0 0 3]
 [5 3 9 0 0 0 8 1 6]
 [8 0 0 5 0 0 0 9 0]
 [0 0 3 1 0 0 0 0 0]
 [6 0 4 0 0 7 0 2 0]
 [9 1 7 0 0 6 5 0 0]]
solution:
[[0 0 1 7 0 0 2 3 5]
 [0 9 0 3 0 0 6 0 8]
 [0 0 0 0 0 4 1 0 0]
 [0 7 9 0 0 9 0 0 3]
 [5 3 9 0 0 0 8 1 6]
 [8 0 0 5 0 0 0 9 0]
 [0 0 3 1 0 0 0 0 0]
 [6 0 4 0 0 7 0 2 0]
 [9 1 7 0 0 6 5 0 0]]


In [8]:
def move(s,e,n=0):
    print ('move disk {} from position {} to position {} !'.format(n,s,e))

In [9]:
move ('A','B')

move disk 0 from position A to position B !


In [8]:
def movevia(a,v,b):
    move(a,v)
    move(v,b)

In [15]:
movevia('A','V','B')

move disk 0 from position A to position V !
move disk 0 from position V to position B !


In [17]:
def hanoi(n,a,b,c):
    if n ==0:
        pass
    else:
        hanoi(n-1,a,c,b)
        move(a,b,n)
        hanoi(n-1,b,a,c)

In [18]:
hanoi(5,'A','B','C')

move disk 1 from position A to position B !
move disk 2 from position A to position C !
move disk 1 from position C to position A !
move disk 3 from position A to position B !
move disk 1 from position B to position C !
move disk 2 from position B to position A !
move disk 1 from position A to position B !
move disk 4 from position A to position C !
move disk 1 from position C to position A !
move disk 2 from position C to position B !
move disk 1 from position B to position C !
move disk 3 from position C to position A !
move disk 1 from position A to position B !
move disk 2 from position A to position C !
move disk 1 from position C to position A !
move disk 5 from position A to position B !
move disk 1 from position B to position C !
move disk 2 from position B to position A !
move disk 1 from position A to position B !
move disk 3 from position B to position C !
move disk 1 from position C to position A !
move disk 2 from position C to position B !
move disk 1 from position B to p